# Generated by Django 3.1.5 on 2021-01-05 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='festevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('details', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('contact', models.CharField(max_length=10)),
                ('no_of_seats', models.IntegerField()),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_time', models.TimeField(default=django.utils.timezone.now)),
                ('isCompatition', models.BooleanField(default=False)),
                ('first_price', models.FloatField()),
                ('second_price', models.FloatField()),
                ('third_price', models.FloatField()),
                ('isGroup', models.BooleanField(default=False)),
                ('max_members', models.IntegerField()),
                ('min_members', models.IntegerField()),
            ],
        ),
    ]
