# Generated by Django 3.1.5 on 2021-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festevent',
            name='first_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festevent',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festevent',
            name='min_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festevent',
            name='no_of_seats',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='festevent',
            name='second_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festevent',
            name='third_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
