# Generated by Django 3.1.5 on 2021-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20210106_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festevent',
            name='banner',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
