# Generated by Django 3.1.4 on 2021-01-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='events',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='events',
            name='fees',
        ),
        migrations.AddField(
            model_name='events',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
