# Generated by Django 3.1.4 on 2021-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210101_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
