# Generated by Django 3.1.4 on 2021-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210103_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='first_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='no_of_seats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='second_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='third_price',
            field=models.FloatField(default=0),
        ),
    ]
