# Generated by Django 3.1.4 on 2021-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210103_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
