# Generated by Django 3.1.4 on 2021-01-03 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210103_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 3, 9, 28, 1, 352650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 9, 28, 1, 352824, tzinfo=utc)),
        ),
    ]
