# Generated by Django 3.1.4 on 2021-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210103_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isGroup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='onOfGroupMembers',
            field=models.TextField(default=1),
        ),
    ]
