# Generated by Django 3.1.4 on 2021-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210103_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='onOfGroupMembers',
            field=models.IntegerField(default=1),
        ),
    ]
