# Generated by Django 3.1.4 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210103_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='onOfGroupMembers',
            new_name='maxNoOfGroupMembers',
        ),
        migrations.AddField(
            model_name='events',
            name='minNoOfGroupMembers',
            field=models.IntegerField(default=1),
        ),
    ]
